[project]
name = "rozetka_keepa"
version = "0"
description = "Rozetka.ua Keepa"
authors = [
    { name = "Alexey ALERT Rubasheff", email = "alexey.rubasheff@gmail.com" }
]
readme = "README.md"
requires-python = "==3.14.*"
keywords = ["rozetka"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = [
    "aiogram",
    "apscheduler",
    "global-logger",
    "passlib",
    "psycopg2-binary",
    "python-dotenv",
    "rozetka-api",
    "sqlalchemy",
    "sqlalchemy-utils",
    "tzdata",
]
[tool.uv]
prerelease = "allow"

[project.urls]
homepage = "https://github.com/ALERTua/rozetka_keepa"
repository = "https://github.com/ALERTua/rozetka_keepa"
documentation = "https://github.com/ALERTua/rozetka_keepa"
"Bug Tracker" = "https://github.com/ALERTua/rozetka_keepa/issues"
"Rozetka API" = "https://github.com/ALERTua/rozetka_api"
"Rozetka Keepa" = "https://github.com/ALERTua/rozetka_keepa"
"Rozetka FastAPI" = "https://github.com/ALERTua/rozetka_fastapi"
"Rozetka UserScript" = "https://github.com/ALERTua/rozetka_userscript"

[dependency-groups]
dev = [
    "pre-commit",
    "pytest",
    "ruff",
]

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = 88

[tool.ruff.lint.pycodestyle]
max-doc-length = 88
max-line-length = 120
